### PR TITLE
Update readme.txt

### PR DESCRIPTION
**Pull request by K-Alette**

### CODE REVIEW

**Review by NashvillePublicLibrary — COMMENTED** [review]
I would like to test merging this pull request TO VERIFY THAT I CANNOT.

**Review by NashvillePublicLibrary — APPROVED** [review]

**Review by NashvillePublicLibrary — APPROVED** [review]
I might be able to approve...

**Review by NashvillePublicLibrary — APPROVED** [review]
... but because I do not have write access I can neither approve-for-real, nor can I merge.

**Comment by NashvillePublicLibrary** [comment]
here's a screen snippet of me NOT being able to approve or merge

image

**Comment by mdnoble73** [comment]
Closing since this isn't a real pull request :D

**Pull request closed without merging**
