### PR TITLE
Updates nashville.aspenlocal config and .idea files

### PR DESCRIPTION
**Pull request by NashvillePublicLibrary**
Updates files related to Nashville development environment

https://trello.com/c/UT5wqd23

### CODE REVIEW

**Comment by mdnoble73** [comment]
I'm torn about committing these.  On one hand it makes it easier to setup new environments on the other hand they are local files that shouldn't be added to git.  What are your thoughts pro/con?

**Comment by NashvillePublicLibrary** [comment]
My off-the-cuff thought:

Posting the jetbrains config files *potentially* helps me, you, and Bryan set up faster  - and *potentially* causes hiccups, which in turn , *potentially* cause us to learn more about what the config means and how to maximize our phpstorm use.

**Comment by mdnoble73** [comment]
I currently have the web project in code/web that should have debuggers etc setup already.  Do you want to try loading that rather than creating a new project?

**Comment by mdnoble73** [comment]
James will move config things to config.pwd and used .gitignore to remove the .idea files

**Pull request closed without merging**
