### PR TITLE
20.15.00 carl x self reg

### PR DESCRIPTION
**Pull request by NashvillePublicLibrary**
@mdnoble73 we will need to do a code review - of selfReg.tpl. I've changed it! Other folks might not like what I've done!

### CODE REVIEW

**Comment by mdnoble73** [comment]
In CARL.X you don't need to translate the labels for each field.  Those are automatically translated when the form is displayed. 

Also, one of the templates is in the nashville subtheme. I'm not sure that is used or needed.

**Comment by NashvillePublicLibrary** [comment]
@mdnoble73 I've made the changes you suggested.

What I want to check in with folks (you) about: I changed the logic of the selfreg tpl file so that non-success + message = display message, do not re-display the form. That's the desired behavior in Nashville - but I don't know about other libraries.

**Comment by mdnoble73** [comment]
Can you resubmit against either 20.15.01 or 20.16.00?

**Comment by NashvillePublicLibrary** [comment]
@mdnoble73 as promised - another update to CarlX SelfReg

**Comment by mdnoble73** [comment]
Changes are all looking good.  Can you resubmit the pull request against 20.16 rather than master?

**Comment by NashvillePublicLibrary** [comment]
D'oh! Resubmitting against 20.16.00

**Review by mdnoble73 — APPROVED** [review]

**Pull request merged**
